# --- Main Colors ---
background            #18120c
foreground            #eee0d4
cursor                #eee0d4
cursor_text_color     #18120c

selection_background  #57432b
selection_foreground  #fcddbd

url_color             #bbcd9e

# --- ANSI Colors ---
color0                #18120c
color1                #ffb4ab
color2                #bbcd9e
color3                #dfc2a2
color4                #f8bb71
color5                #bbcd9e
color6                #dfc2a2
color7                #eee0d4

color8                #504539
color9                #93000a
color10               #3d4c27
color11               #57432b
color12               #653e00
color13               #57432b
color14               #3d4c27
color15               #d4c4b5

# --- Starship Prompt Bubbles ---
color255              #653e00
color254              #f8bb71
color253              #57432b
color252              #dfc2a2
color251              #3d4c27
color250              #bbcd9e
color249              #93000a
color248              #ffb4ab

color232              #ffddb8
color233              #472a00
color234              #fcddbd
color235              #3f2d17
color236              #d7e9b8
color237              #273513
color238              #ffdad6
color239              #690005
color240              #ffddb8

# Matched with unthemed light/dark
color243              #f8bb71
color244              #ffb4ab
color245              #504539

# --- UI Elements ---
active_tab_foreground   #472a00
active_tab_background   #f8bb71
inactive_tab_foreground #ffddb8
inactive_tab_background #653e00

active_border_color     #f8bb71
inactive_border_color   #9c8e80

# --- Marks ---
mark1_foreground        #2a1700
mark1_background        #ffddb8
mark2_foreground        #281805
mark2_background        #fcddbd
mark3_foreground        #131f02
mark3_background        #d7e9b8
